title: Lev1yLab
navbar_title: Home

author:
  name: Levi Yang # Your name
  email: leviyangms@protonmail.com

description: Personal blog # description of your site

url: "https://lev1y.github.io/" # The base hostname & protocol for your site, e.g. http://example.com
baseurl: "/academic" # The subpath of your site, e.g. /blog

jekyllacademic:
  homepage_title: Hi, I am Levi. <br> I develop innovative technologies for <br> our sustainable future. # Your homepage title
  disqusname: # Your disqus sitename
  footer: Levi Yang, 2021 # Your name, Year
  contentlicense: "MIT" # Choose either one of these to put: MIT, Commons Clause, CC BY 4.0, CC BY-NC 4.0, CC BY-ND 4.0, CC BY-NC-ND 4.0, CC BY-NC-SA 4.0, CC BY-NC-SA 4.0, CC BY-SA 4.0
  socials:
    #twitter: twitter # Your twitter username
    #github: yak-fumblepack/jekyll-academic # Your github username
    #linkedin: unavailable # Your linkedin
    #keybase: keybase # Your keybase

# No need to edit this part, however if you want to, that's fine as well

permalink: pretty
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter_opts:
    disable: true

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:year/:month/:day/:slug
  projects:
    output: true
    permalink: /:collection/:title

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
